name: weatherApp
description: weather reporting app
dependencies:
  browser: any
  event_bus: any
  google_maps: any
  http: any
  js: any
  logging: any
  logging_handlers: any
  unittest: any
  web_ui: any
